### Register

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username":"admin",
  "email":"admin@mail.fr",
  "password":"admin"
}
### Login

###Admin user
POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"admin",
  "password":"admin"
}

###Not admin user
POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"titi",
  "password":"titi"
}
### user 2
POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"pierre",
  "password":"pierre"
}