### Register

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username":"boubou",
  "email":"boubou@mail.fr",
  "password":"boubou"
}
### Login

POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"toto",
  "password":"toto"
}