### Register

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username":"popo",
  "email":"popo@mail.fr",
  "password":"popo"
}
### Login

###Admin user
POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"popo",
  "password":"popo"
}

###Not admin user
POST http://localhost:5000/auth/login
Content-Type: application/json

{ 
  "username":"titi",
  "password":"titi"
}