HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 294
ETag: W/"126-6ppZWwXZyD7jM0VAsxOpSbxSOcg"
Date: Fri, 28 Apr 2023 10:07:04 GMT
Connection: close

{
  "id": "644ed1b568703df6e8b0cc53",
  "email": "admin@mail.fr",
  "username": "admin",
  "isAdmin": true,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMWI1Njg3MDNkZjZlOGIwY2M1MyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4Mjg4NzQ5MCwiZXhwIjoxNjgyOTczODkwfQ.lBtRNuNhEcOFxJvvaeL30PUi-y3OALH8UEg_KmYlymM",
  "exp": 1682973890
}

{
  "id": "644ed130427b3b0b260bac97",
  "email": "titi@mail.fr",
  "username": "titi",
  "isAdmin": false,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI4ODc1MTIsImV4cCI6MTY4Mjk3MzkxMn0.2m6F0CYNC-D7RburZWErZ9cDIS1ug-EUpMWUtrSt2gM",
  "exp": 1682973912
}

{
  "id": "644ed12b427b3b0b260bac94",
  "email": "pierre@mail.fr",
  "username": "pierre",
  "isAdmin": false,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTJiNDI3YjNiMGIyNjBiYWM5NCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI4ODc1MjMsImV4cCI6MTY4Mjk3MzkyM30.lUSt7XXTAqqDOArhUOz8US5irilyWqkUBqwi83Rw5aY",
  "exp": 1682973923
}