HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 294
ETag: W/"126-6ppZWwXZyD7jM0VAsxOpSbxSOcg"
Date: Fri, 28 Apr 2023 10:07:04 GMT
Connection: close

{
  "id": "644ed1b568703df6e8b0cc53",
  "email": "admin@mail.fr",
  "username": "admin",
  "isAdmin": true,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMWI1Njg3MDNkZjZlOGIwY2M1MyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY4Mjg4NzQ5MCwiZXhwIjoxNjgyOTczODkwfQ.lBtRNuNhEcOFxJvvaeL30PUi-y3OALH8UEg_KmYlymM",
  "exp": 1682973890
}

{
  "id": "644ed130427b3b0b260bac97",
  "email": "titi@mail.fr",
  "username": "titi",
  "isAdmin": false,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk2MDcsImV4cCI6MTY4MzA2NjAwN30.ffwThGLVv-6BWtSw_DdpedHg0hvvHWl1AX0in_jRjqw",
  "exp": 1683066007
}

{
  "id": "644ed12b427b3b0b260bac94",
  "email": "pierre@mail.fr",
  "username": "pierre",
  "isAdmin": false,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTJiNDI3YjNiMGIyNjBiYWM5NCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk4ODksImV4cCI6MTY4MzA2NjI4OX0.hwz9yixEfv3Qnk9OpnOjYC1DTEbnWaOdF1cCwx3L6r4",
  "exp": 1683066289
}
// Touite 

{
  "text": "Titi first touite after admin add verifyTokenAndTouiteAuthorization.",
  "author": "644ed130427b3b0b260bac97",
  "_id": "64503c264cc172028ee5b199",
  "createdAt": "2023-05-01T22:24:38.735Z",
  "updatedAt": "2023-05-01T22:24:38.735Z",
  "__v": 0
}