### To use it, you will need to install the "humao.rest-client" extension created by Huachao Mao.

### Add one touite
POST http://localhost:5000/touites/new
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk2MDcsImV4cCI6MTY4MzA2NjAwN30.ffwThGLVv-6BWtSw_DdpedHg0hvvHWl1AX0in_jRjqw
Content-Type: application/json

{
  "text":"Titi first touite after admin add verifyTokenAndTouiteAuthor"
}

### Delete one touite
DELETE  http://localhost:5000/touites/6451770b4d02048c455b40f4
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk2MDcsImV4cCI6MTY4MzA2NjAwN30.ffwThGLVv-6BWtSw_DdpedHg0hvvHWl1AX0in_jRjqw

### Update one touite
PUT http://localhost:5000/touites/6451770b4d02048c455b40f4
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk2MDcsImV4cCI6MTY4MzA2NjAwN30.ffwThGLVv-6BWtSw_DdpedHg0hvvHWl1AX0in_jRjqw
Content-Type: application/json

{
"text": "Hi, It's toto's FIRST text updated !"
}

### Get one touite
Get http://localhost:5000/touites/6451770b4d02048c455b40f4
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTJiNDI3YjNiMGIyNjBiYWM5NCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk4ODksImV4cCI6MTY4MzA2NjI4OX0.hwz9yixEfv3Qnk9OpnOjYC1DTEbnWaOdF1cCwx3L6r4

### Get all touites
Get http://localhost:5000/touites/
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGVkMTMwNDI3YjNiMGIyNjBiYWM5NyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2ODI5Nzk2MDcsImV4cCI6MTY4MzA2NjAwN30.ffwThGLVv-6BWtSw_DdpedHg0hvvHWl1AX0in_jRjqw

### Delete all touites

DELETE http://localhost:5000/touites/deleteAll/644952c5cae71403e639347e
Authorization: bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDQ5NTJjNWNhZTcxNDAzZTYzOTM0N2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODI4ODQxNjUsImV4cCI6MTY4Mjk3MDU2NX0.aU3AcFTvNPkxQvaWs_MzUlpQSDEKHo1r205HgdoTm_4